---
- hosts: nfs_clients
  become: yes
  tasks:
    - name: install nfs-utils
      yum: name=nfs-utils state=latest

    - name: Create a mountable directory if it does not exist
      file:
        path: /mnt/k8sdata
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0775'
    - name: Mount volume
      shell: sudo mount 192.168.1.100:/home/vagrant/k8sdata /mnt/k8sdata